# Generated by Django 5.1.2 on 2024-10-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("c_id", models.IntegerField()),
                ("u_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
