# Generated by Django 5.1.2 on 2024-10-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo1", "0002_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="update_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
