# Generated by Django 5.1.2 on 2024-10-30 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo1", "0003_article_update_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="demo1.category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="userinfo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="demo1.userinfo",
            ),
            preserve_default=False,
        ),
    ]
