# Generated by Django 5.1.2 on 2024-10-30 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo1", "0004_article_category_article_userinfo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="category",
        ),
        migrations.RemoveField(
            model_name="article",
            name="userinfo",
        ),
        migrations.AlterField(
            model_name="article",
            name="c_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="demo1.category",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="u_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="demo1.userinfo",
            ),
        ),
    ]
