# Generated by Django 5.1.2 on 2024-10-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo1", "0005_remove_article_category_remove_article_userinfo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="c_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="article",
            name="u_id",
            field=models.IntegerField(),
        ),
    ]
